#service

#keyStore.keyStoreLoc=C:/CA/O000170.jks
#KeyStore.keyPassWord=mfds2015
#keyStore.keyAlias=O000170
#fileDownloadPath=C:/mfdshome/files/client
#wslimsUrl=https://wslims.mfds.go.kr

#dev
keyStore.keyStoreLoc=C:/CA/1471124.jks
KeyStore.keyPassWord=mfds2015
keyStore.keyAlias=1471124
fileDownloadPath=/mfdshome/files/client
wslimsUrl=http://localhost:8061
